services:
  postgresql:
    image: postgres:15.1-alpine3.17
    container_name: postgresql
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=magellan
      - POSTGRES_PASSWORD=magellan
      - POSTGRES_DB=magellan
