// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: magellan/authentication/v1/service.proto

package authenticationv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Login
	//
	// {{.MethodDescriptorProto.Name}} is used for login to the system. Define `loginType` and one of `loginDetails`
	// HTTPOnly Cookie will be set under the name `mat` as Access Token and `mrt` as Refresh Token only if the Login success
	// otherwise 401 will be returned
	Login(ctx context.Context, in *ServiceLoginRequest, opts ...grpc.CallOption) (*ServiceLoginResponse, error)
	// Logout
	//
	// {{.MethodDescriptorProto.Name}} is used for logout from the system
	// HTTPOnly Cookie `mat` and `mrt` will be unset
	Logout(ctx context.Context, in *ServiceLogoutRequest, opts ...grpc.CallOption) (*ServiceLogoutResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Login(ctx context.Context, in *ServiceLoginRequest, opts ...grpc.CallOption) (*ServiceLoginResponse, error) {
	out := new(ServiceLoginResponse)
	err := c.cc.Invoke(ctx, "/magellan.authentication.v1.Service/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Logout(ctx context.Context, in *ServiceLogoutRequest, opts ...grpc.CallOption) (*ServiceLogoutResponse, error) {
	out := new(ServiceLogoutResponse)
	err := c.cc.Invoke(ctx, "/magellan.authentication.v1.Service/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// Login
	//
	// {{.MethodDescriptorProto.Name}} is used for login to the system. Define `loginType` and one of `loginDetails`
	// HTTPOnly Cookie will be set under the name `mat` as Access Token and `mrt` as Refresh Token only if the Login success
	// otherwise 401 will be returned
	Login(context.Context, *ServiceLoginRequest) (*ServiceLoginResponse, error)
	// Logout
	//
	// {{.MethodDescriptorProto.Name}} is used for logout from the system
	// HTTPOnly Cookie `mat` and `mrt` will be unset
	Logout(context.Context, *ServiceLogoutRequest) (*ServiceLogoutResponse, error)
}

// UnimplementedServiceServer should be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Login(context.Context, *ServiceLoginRequest) (*ServiceLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedServiceServer) Logout(context.Context, *ServiceLogoutRequest) (*ServiceLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magellan.authentication.v1.Service/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Login(ctx, req.(*ServiceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magellan.authentication.v1.Service/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Logout(ctx, req.(*ServiceLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "magellan.authentication.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Service_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Service_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magellan/authentication/v1/service.proto",
}
